### ISSUE TITLE
Updating multiple aggregates in the same transaction?

### ISSUE THREAD

**Issue by mpontus** [VaughnVernon/IDDD_Samples#48]
Inside [`ProductApplicationService`](https://github.com/VaughnVernon/IDDD_Samples/blob/master/iddd_agilepm/src/main/java/com/saasovation/agilepm/application/product/ProductApplicationService.java) there appears to be a transaction boundary, culminated with `ApplicationServiceLifeCycle.success(). 

It wraps calls to multiple repositories, which, to my understanding, saves changes made in two distinct aggregate roots:

https://github.com/VaughnVernon/IDDD_Samples/blob/9b27b11773f62afb5d1b541abf51fb36516a7250/iddd_agilepm/src/main/java/com/saasovation/agilepm/application/product/ProductApplicationService.java#L57-L85

I want to make sure that I'm not missing any important context here. As per Vernon's [own words](https://vaughnvernon.co/wordpress/wp-content/uploads/2014/10/DDD_COMMUNITY_ESSAY_AGGREGATES_PART_1.pdf):

> A properly designed aggregate is one that can be modified in any way required by the business with its invariants completely consistent within a single transaction. And a properly designed bounded context modifies only one aggregate instance per transaction in all cases. 

Is this an example of a situation where the rule of thumb does not apply? Does anyone have a better explanation?

**Comment by VaughnVernon** [comment]
@mpontus I don't recall all the reasons for this, but I think the `Product` and `TimeConstrainedProcessTracker` always change together. If either change would succeed/fail they would both succeed/fail together. This could be modeled differently, and possibly better, if the process was considered pending or completed by the `discussionId` being set.

You'll find that approach in the way user roles of the `team` module:

https://github.com/VaughnVernon/IDDD_Samples/blob/9b27b11773f62afb5d1b541abf51fb36516a7250/iddd_agilepm/src/main/java/com/saasovation/agilepm/domain/model/team/Member.java#L24

It's completely internal and is overall a better/safer model. I have a talk from 5 years ago that takes up this subject, "Modeling Uncertainty." The original discussion using the `team` example is found in Chapter 13 of my red book, "Implementing Domain-Driven Design."

This is my favorite recording of the talk as I had a lot of fun on that day: https://youtu.be/8Y-XPlXOWoA

**Comment by mpontus** [comment]
@VaughnVernon 

I must admit that some of the things you said in the talk went over my head, but it will probably get better on the second watch which I'm sure I'll do in the future.

You are phenomenal. Thank you for the explanation.

**Comment by VaughnVernon** [comment]
Thanks for sharing your kind thoughts, @mpontus. I'm glad I could help.

```
<shameless-plug>In case it would help I have an upcoming public IDDD Workshop.</shameless-plug>
```
